platform :ios, '13.0'

target 'Moa' do
  use_frameworks!
  # RxSwift
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxGesture', '~> 3.0'
  pod 'RxDataSources', '~> 4.0'  
  pod 'RxKeyboard'
  # Network
  pod 'Moya', '~> 14.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'Kingfisher', '~> 7.0'  
  # Pager
  # pod 'FSPagerView'
  pod 'RxFSPagerView'
end
